/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED.h"
#include "LED_aliases.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "DI_Fdg.h"
#include "DI_Fdg_aliases.h"
#include "DI_Fdd.h"
#include "DI_Fdd_aliases.h"
#include "DI_ATU.h"
#include "DI_ATU_aliases.h"
#include "DI_Index.h"
#include "DI_Index_aliases.h"
#include "DI_PhiA.h"
#include "DI_PhiA_aliases.h"
#include "DI_PhiB.h"
#include "DI_PhiB_aliases.h"
#include "QuadDec.h"
#include "ENA_L298.h"
#include "ENA_L298_aliases.h"
#include "Clock_1.h"
#include "Stat_dir.h"
#include "PWM.h"
#include "IN2_L298.h"
#include "IN2_L298_aliases.h"
#include "IN1_L298.h"
#include "IN1_L298_aliases.h"
#include "Clock_2.h"
#include "Speed.h"
#include "FECH.h"
#include "isr_fech.h"
#include "Clock_3.h"
#include "Clock_4.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_SCB_IRQ.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

